name: Build Bicep to ARM Template
permissions:
      actions: write
      checks: write
      contents: write
on: 
  push:
    paths:
      - '**/main.bicep'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: |
          main.bicep

    - name: Find and build Bicep files
      shell: bash
      run: |
        bicepFile=$(echo '${{ steps.changed-files.outputs.all_changed_files }}
        dirPath=$(dirname "$bicepFile")
        outputFile=$(echo "$dirPath/main.json")
        az bicep build --file "$bicepFile" --outfile "$outputFile"

    - name: Commit ARM template
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add main.json
        git commit -m 'Add ARM template'
        git push