name: Build Bicep to ARM Template

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Bicep file
      uses: Azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: 'main.bicep'
        outputFilePath: 'main.json'
    
    - name: Test action output
        shell: bash
        run: |
          FILE="./main.json"
          if test -f "$FILE"; then
            echo "$FILE created successfully"
          else
            echo "$FILE not found."
            exit 1
          fi
    
    - name: Commit ARM template
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add main.json
        git commit -m 'Add ARM template'
        git push