name: Build Bicep to ARM Template

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Bicep file
      uses: Azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: 'main.bicep'
        outputFilePath: 'main.json'
    