name: Build Bicep to ARM Template
permissions:
      actions: write
      checks: write
      contents: write
on: 
  push:
    paths:
      - 'templates/**/main.bicep'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Get main.bicep path
    #   id: get_bicep_path
    #   run: |
    #     bicepFile=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep 'main.bicep')
    #     dirPath=$(dirname "$bicepFile")
    #     echo "armtFile=$dirPath" >> $GITHUB_ENV
    #     az bicep build --file "$bicepFile" --out "$armtFile"

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: |
          main.bicep

    - name: List changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done

    # - name: Commit ARM template
    #   run: |
    #     git config --global user.name 'github-actions[bot]'
    #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    #     git add "$armtFile"
    #     git commit -m 'Add ARM template'
    #     git push