name: Build Bicep to ARM Template
permissions:
      actions: write
      checks: write
      contents: write
on: 
  push:
    paths:
      - '**/main.bicep'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find and build Bicep files
      shell: bash
      run: |
        find . -name 'main.bicep' | while read bicepFile; do
          dir=$(dirname "$bicepFile")
          outputFile="$dir/main.json"
          echo "Building $bicepFile to $outputFile"
          az bicep build --file "$bicepFile" --outfile "$outputFile"
        done
    
    - name: Test action output
      shell: bash
      run: |
        FILE="./main.json"
        if test -f "$FILE"; then
          echo "$FILE created successfully"
        else
          echo "$FILE not found."
          exit 1
        fi
    
    - name: Commit ARM template
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add main.json
        git commit -m 'Add ARM template'
        git push